package dev.jceballos.stockpile.infrastructure.ui;

import dev.jceballos.stockpile.inventory.application.command.RegisterProductCommandHandler;
import dev.jceballos.stockpile.inventory.application.query.ProductQueryHandler;
import dev.jceballos.stockpile.order.application.command.AddProductToOrderCommandHandler;
import dev.jceballos.stockpile.order.application.command.CancelOrderCommandHandler;
import dev.jceballos.stockpile.order.application.command.DispatchOrderCommandHandler;
import dev.jceballos.stockpile.order.application.command.PayOrderCommandHandler;
import dev.jceballos.stockpile.order.application.query.OrderQueryHandler;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

public class MainFrame extends JFrame {
    private final JPanel rootPanel;

    private final RegisterProductCommandHandler registerProductCommandHandler;
    private final ProductQueryHandler productQueryHandler;
    private final AddProductToOrderCommandHandler addProductToOrderCommandHandler;
    private final CancelOrderCommandHandler cancelOrderCommandHandler;
    private final PayOrderCommandHandler payOrderCommandHandler;
    private final DispatchOrderCommandHandler dispatchOrderCommandHandler;
    private final OrderQueryHandler orderQueryHandler;

    public MainFrame(RegisterProductCommandHandler registerProductCommandHandler, ProductQueryHandler productQueryHandler, AddProductToOrderCommandHandler addProductToOrderCommandHandler, CancelOrderCommandHandler cancelOrderCommandHandler, PayOrderCommandHandler payOrderCommandHandler, DispatchOrderCommandHandler dispatchOrderCommandHandler, OrderQueryHandler orderQueryHandler) {
        {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
            rootPanel = new JPanel();
            rootPanel.setLayout(new GridBagLayout());
            final JLabel label1 = new JLabel();
            label1.setText("Bienvenido a Stockpile");
            GridBagConstraints gbc;
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.anchor = GridBagConstraints.WEST;
            rootPanel.add(label1, gbc);
            final JPanel spacer1 = new JPanel();
            gbc = new GridBagConstraints();
            gbc.gridx = 1;
            gbc.gridy = 0;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            rootPanel.add(spacer1, gbc);
            final JPanel spacer2 = new JPanel();
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 1;
            gbc.fill = GridBagConstraints.VERTICAL;
            rootPanel.add(spacer2, gbc);
        }

        this.registerProductCommandHandler = Objects.requireNonNull(registerProductCommandHandler);
        this.productQueryHandler = Objects.requireNonNull(productQueryHandler);
        this.addProductToOrderCommandHandler = Objects.requireNonNull(addProductToOrderCommandHandler);
        this.cancelOrderCommandHandler = Objects.requireNonNull(cancelOrderCommandHandler);
        this.payOrderCommandHandler = Objects.requireNonNull(payOrderCommandHandler);
        this.dispatchOrderCommandHandler = Objects.requireNonNull(dispatchOrderCommandHandler);
        this.orderQueryHandler = Objects.requireNonNull(orderQueryHandler);

        setTitle("Stockpile");
        setContentPane(rootPanel);
        setJMenuBar(buildMenuBar());
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 600);
        setLocationRelativeTo(null);
    }

    private JMenuBar buildMenuBar() {
        JMenuBar menuBar = new JMenuBar();

        JMenu catalogMenu = new JMenu("Catálogo");
        JMenuItem viewProductsItem = new JMenuItem("Ver productos");
        JMenuItem registerProductItem = new JMenuItem("Registrar producto");
        viewProductsItem.addActionListener(e -> onViewProducts());
        registerProductItem.addActionListener(e -> onRegisterProduct());
        catalogMenu.add(viewProductsItem);
        catalogMenu.add(registerProductItem);

        JMenu ordersMenu = new JMenu("Pedidos");
        JMenuItem viewOrdersItem = new JMenuItem("Ver pedidos");
        JMenuItem newOrderItem = new JMenuItem("Nuevo pedido");
        viewOrdersItem.addActionListener(e -> onViewOrders());
        newOrderItem.addActionListener(e -> onNewOrder());
        ordersMenu.add(viewOrdersItem);
        ordersMenu.add(newOrderItem);

        menuBar.add(catalogMenu);
        menuBar.add(ordersMenu);
        return menuBar;
    }

    private void onViewProducts() {
        JOptionPane.showMessageDialog(this, "Pantalla de productos: pendiente (próximo paso)");
    }

    private void onRegisterProduct() {
        JOptionPane.showMessageDialog(this, "Alta de producto: pendiente (próximo paso)");
    }

    private void onViewOrders() {
        JOptionPane.showMessageDialog(this, "Pantalla de pedidos: pendiente (próximo paso)");
    }

    private void onNewOrder() {
        JOptionPane.showMessageDialog(this, "Nuevo pedido: pendiente (próximo paso)");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
